

on:
  push:
    branches:
      - main


jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repo
        uses: actions/checkout@v4

      - name:  Register QEMU emulators (arm64, etc.)
        uses: docker/setup-qemu-action@v3

      - name: Spin up a Buildx builder (docker-container driver = multi-arch)
        uses: docker/setup-buildx-action@v3


      - name: Log in to Docker Hub (or GHCR, ACR…)
        uses: docker/login-action@v3
        with:
          username: greenh47
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push the arm64 image
        uses: docker/build-push-action@v5    # single step does it all :contentReference[oaicite:4]{index=4}
        with:
          context: .
          #file: Dockerfile.prod
          file: Dockerfile
          platforms: linux/arm64            # your target architecture
          push: true
          tags: greenh47/homepage:nextjs

      - name: Update docker image
        id: update-ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/homepage-fumadocs
            
            # stop docker compose
            sudo docker compose down home_page

            # pull the latest image
            sudo docker compose pull home_page

            # start the docker compose
            sudo docker compose up -d home_page
